### ISSUE TITLE
Unable to import KiCAD files

### ISSUE THREAD

**Issue by clemc98** [matthuszagh/pyems#36]
Hi, I know your program could create .KiCAD files. I'm interesting to import files create with KiCAD to import and analyse them with pyems.
Is it possible to do it ?

**Comment by matthuszagh** [comment]
This is not possible with pyems and probably won't be supported. If you have a workflow that you think may be useful to others feel free to share it and maybe it will change my mind. However, I don't currently feel that kicad is particularly good at creating precise microwave structures.

In any event, [pcbmodelgen](https://github.com/jcyrax/pcbmodelgen) is a tool that is intended to do exactly this. I haven't used it much so I can't speak to how well it works.

An alternative solution would be to export from kicad to hyperlynx and then to import that into openems ([tutorial](https://openems.de/index.php/Tutorial:_Importing_with_hyp2mat.html)). [Kicad has at least some support for hyperlynx](https://docs.kicad.org/doxygen/classHYPERLYNX__EXPORTER.html), although last I checked it needed work.
