### ISSUE TITLE
Run without user confirmation

### ISSUE THREAD

**Issue by clemc98** [matthuszagh/pyems#41]
Hi, i would run consecutively some simulation. Can i run the simulation without running Appcsxcad and without asking to the user : Continue simulation (y/n)?

**Comment by matthuszagh** [comment]
This is indeed possible. Calling [Simulation.run(csx=false)](https://github.com/matthuszagh/pyems/blob/249de1d2cf489afada0d8d154dfa429f2595a166/pyems/simulation.py#L163) will do the trick. This is done, for example, here (and I generally use it when performing parameter sweeps):

https://github.com/matthuszagh/pyems/blob/55b9d34163e10273018e39974f16943c1e67b885/examples/microstrip_width_sweep.py#L51

I've added documentation to `run()` explaining the parameters in 249de1d2cf489afada0d8d154dfa429f2595a166.
