### ISSUE TITLE
Limit threads in simulation

### ISSUE THREAD

**Issue by dom11990** [matthuszagh/pyems#42]
Is it possible to limit the number of threads through your interface? The python openems interface has this functionality in the simulation "run" call. Without it, my simulation runs painfully slow. Generally, oems recommends running on two threads anyway so perhaps it would be useful to set this as the default?

http://www.openems.de/forum/viewtopic.php?f=3&t=137

**Comment by matthuszagh** [comment]
I added this in 625dddb03fe67b715e3006bbb26931015c756d2e. It's a very simple change so I haven't actually tested it yet. Let me know if you run into any issues.

**Comment by matthuszagh** [comment]
Closing. Feel free to reopen if that didn't work for you.
