### ISSUE TITLE
Fully manual meshing & pyems equivalent to AddLumpedPort

### ISSUE THREAD

**Issue by 0xCoto** [matthuszagh/pyems#58]
Currently playing around with pyems now that things are running smoothly. The first thing I'm trying to do is migrate my Octave openEMS [script](https://github.com/0xCoto/OpenEMS-Notes/blob/main/accurate_sim.m) (which works well and can be used as reference) to pyems.

I'm facing two main issues that I've been trying to resolve:
1. While openEMS does not support automatic meshing at all, pyems' automatic mesh isn't ideal either (although it looks somewhat more promising). Does pyems allow you to manually feed in the mesh line positions like Octave? I.e. provide three 1D arrays (or one 3D array) to construct the mesh like that. That'd really help me experiment with some custom meshing libraries! Am I supposed to iterate the input arrays over the [`add_line_manual()`](https://github.com/matthuszagh/pyems/blob/master/pyems/mesh.py#L1031) function? I couldn't find a pyems example that relies solely on manual meshing.
2. Regarding the port, I've been using [`AddLumpedPort`](https://github.com/0xCoto/OpenEMS-Notes/blob/main/accurate_sim.m#L106) in Octave, which works great as a simple discrete 50 Ω port. Which type of port serves as its equivalent in pyems? I played around with a couple of classes found in [`port.py`](https://github.com/matthuszagh/pyems/blob/master/pyems/port.py), with little luck.

**Comment by 0xCoto** [comment]
@matthuszagh Thanks! For now, I've managed to deal with the pre-processing separately. What I'm now curious about is post-processing. Given I've run a simulation without pyems (e.g. generated the XML with Octave and got some results), is it possible to process and view the results (S11, farfield and E-field) with pyems?

My understanding is that the postprocessing utilities (`print_table` and `Simulation.view_field`) depend on the `Simulation` class, but is it possible for pyems to output results without it (e.g. using the generated XML file), or must everything have been generated through pyems?

The original Octave functions that take care of postprocessing is [`CalcNF2FF.m`](https://github.com/thliebig/openEMS/blob/master/matlab/CalcNF2FF.m) and [`ReadUI.m`](https://github.com/thliebig/openEMS/blob/master/matlab/ReadUI.m), so I'd be curious to know if `pyems` already includes some kind of implementation so I don't have to rewrite them in python.

**Comment by matthuszagh** [comment]
> The original Octave functions that take care of postprocessing is [CalcNF2FF.m](https://github.com/thliebig/openEMS/blob/master/matlab/CalcNF2FF.m) and [ReadUI.m](https://github.com/thliebig/openEMS/blob/master/matlab/ReadUI.m), so I'd be curious to know if pyems already includes some kind of implementation so I don't have to rewrite them in python.

Take a look at the interface provided by openems. For example, [nf2ff.py](https://github.com/thliebig/openEMS/blob/master/python/openEMS/nf2ff.py) and [ports.py](https://github.com/thliebig/openEMS/blob/master/python/openEMS/ports.py). FYI it seems I was wrong about openems not implementing lumped ports. It's [in that same ports.py file](https://github.com/thliebig/openEMS/blob/d4448fa294723be9bfe270db8ff751faf97c8b85/python/openEMS/ports.py#L143).

As for print_table etc it doesn't really make sense to use pyems just for this - a lot of those data display and viewing functions are really simple and just provided as a convenience.
